# Generated by Django 3.0.5 on 2021-12-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
